### ISSUE TITLE
Debug build failure on debian

### ISSUE THREAD

**Issue by emilio** [servo/mozjs#106]
@anholt over in https://github.com/servo/servo/pull/13629:

> I haven't marked ./mach build -d as passing because it's failing for me in mozjs:
> 
>     /home/anholt/src/servo/servo/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/master/mozjs/js/src/old-configure: 72: ./config.cache: Syntax error: Unterminated quoted string
> 
> However, it's also failing without this patch.  ./mach build -r is succeeding.

@anholt: Does it work if you remove the build directory to do a clean build (`rm -rf target/debug/`)?

I had mozjs issues today too (https://github.com/servo/servo/issues/13619). Doesn't seem like it but...

**Comment by anholt** [comment]
Looks like nuking target/debug/build/mozjs* was sufficient.  Thanks!

**Comment by emilio** [comment]
Closing this then, no problem! :)
