### ISSUE TITLE
ForOfIterator padding is not always generated by bindgen

### ISSUE THREAD

**Issue by asajeffrey** [servo/mozjs#154]
As reported by @paulrouget in https://github.com/servo/servo/issues/21773:
```
error[E0063]: missing field `__bindgen_padding_0` in initializer of `mozjs_sys::root::JS::ForOfIterator`
   --> /Users/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/mozjs-0.9.1/src/conversions.rs:604:28
    |
604 |         let mut iterator = ForOfIterator {
    |                            ^^^^^^^^^^^^^ missing `__bindgen_padding_0`
error: aborting due to previous error
```

**Comment by asajeffrey** [comment]
IRC chat with @emilio and @jdm at https://mozilla.logbot.info/servo/20180921#c15352009

TL;DR: our current guess is that it depends on the libclang version, 6 appears to generate it, 4 appears not to. 

We can't rely on llvm 6, unless wer'e prepared to insist on Ubuntu 18.04, which will constrain us a lot, e.g. in terms of CI.

@emilio suggests deriving Default, and using it in servo, which seems like the most elegant solution.

**Comment by paulrouget** [comment]
For some reason, it's working now. Not sure why.
