### ISSUE TITLE
Avoid full rebuilds with nightly updates?

### ISSUE THREAD

**Issue by Neurrone** [servo/mozjs#155]
Hi,

When updating nightlies, it triggers a full rebuild of mozjs-sys, which takes 20+ mins on my machine.

It would be nice if it checked for the presence of the .lib files in the output directory, and only build the c++ libraries if not found.

**Comment by nox** [comment]
Cargo on its own thrashes the target directory when it detects a new Rust version, AFAIK there is nothing we can do.

Not that I would trust anything that managed to reuse the C++ artefacts on rustup anyway.
