### ISSUE TITLE
python 2.7 only?

### ISSUE THREAD

**Issue by adrian-rt** [servo/mozjs#199]
hi all,

does this work only with python 2.7? 
I only want to run mozwebidlcodegen

thanks,

**Comment by jdm** [comment]
This repository only works with python 2.7.

**Comment by saschanaz** [comment]
Probably time to consider migration...

**Comment by jdm** [comment]
That is work that is ongoing upstream, presumably.

**Comment by jdm** [comment]
Python 2.x is no longer used.
