### ISSUE TITLE
Spurious rebuilds because of writes to the source directory

### ISSUE THREAD

**Issue by SimonSapin** [servo/mozjs#202]
This also affects servo with Rust 1.40 nightly-2019-09-27.

Steps to reproduce with commit 3cfd5e764ea458f759192722a183ff0f235691dc of this repository, Rust 1.38.0:

```rust
cargo clean
cargo build
CARGO_LOG=cargo::core::compiler::fingerprint=info cargo build
cargo build
```

Expected result: the second and third build do nothing, because everything is up to date.

Actual result: in the second build, Cargo runs the build script for `mozjs_sys` again because it considers the previous output to be stale. The third build does nothing as expected. It seems a stable state was reached.

Part of the output that seems most relevant:

```rust
stale: changed "/home/simon/projects/mozjs/mozjs/third_party/python/psutil/tmp"
          (vs) "/home/simon/projects/mozjs/target/debug/build/mozjs_sys-cb3e736023717280/output"
               FileTime { seconds: 1569670020, nanos: 460660576 } != FileTime { seconds: 1569670021, nanos: 808663540 }
```

<details>
<summary>Full output:</summary>

```rust
   Compiling memchr v2.2.1
   Compiling version_check v0.1.5
   Compiling libc v0.2.62
   Compiling cc v1.0.45
   Compiling byteorder v1.3.2
   Compiling glob v0.3.0
   Compiling bitflags v1.2.0
   Compiling proc-macro2 v1.0.4
   Compiling log v0.4.8
   Compiling lazy_static v1.4.0
   Compiling unicode-width v0.1.6
   Compiling cfg-if v0.1.10
   Compiling regex-syntax v0.6.12
   Compiling quick-error v1.2.2
   Compiling unicode-xid v0.2.0
   Compiling termcolor v1.0.5
   Compiling vec_map v0.8.1
   Compiling bindgen v0.51.1
   Compiling ansi_term v0.11.0
   Compiling strsim v0.8.0
   Compiling pkg-config v0.3.16
   Compiling same-file v1.0.5
   Compiling shlex v0.1.1
   Compiling peeking_take_while v0.1.2
   Compiling thread_local v0.3.6
   Compiling textwrap v0.11.0
   Compiling humantime v1.3.0
   Compiling walkdir v2.2.9
   Compiling nom v4.2.3
   Compiling clang-sys v0.28.1
   Compiling rustc-hash v1.0.1
   Compiling quote v1.0.2
   Compiling aho-corasick v0.7.6
   Compiling atty v0.2.13
   Compiling which v3.0.0
   Compiling clap v2.33.0
   Compiling libloading v0.5.2
   Compiling libz-sys v1.0.25
   Compiling cexpr v0.3.5
   Compiling regex v1.3.1
   Compiling env_logger v0.6.2
   Compiling mozjs_sys v0.67.1 (/home/simon/projects/mozjs)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 32s
[2019-09-28T11:28:23Z INFO  cargo::core::compiler::fingerprint] stale: changed "/home/simon/projects/mozjs/mozjs/third_party/python/psutil/tmp"
[2019-09-28T11:28:23Z INFO  cargo::core::compiler::fingerprint]           (vs) "/home/simon/projects/mozjs/target/debug/build/mozjs_sys-cb3e736023717280/output"
[2019-09-28T11:28:23Z INFO  cargo::core::compiler::fingerprint]                FileTime { seconds: 1569670020, nanos: 460660576 } != FileTime { seconds: 1569670021, nanos: 808663540 }
[2019-09-28T11:28:23Z INFO  cargo::core::compiler::fingerprint] fingerprint error for mozjs_sys v0.67.1 (/home/simon/projects/mozjs)/Build/Target { doctest: false, ..: lib_target("mozjs_sys", ["lib"], "/home/simon/projects/mozjs/src/lib.rs", Edition2015) }
[2019-09-28T11:28:23Z INFO  cargo::core::compiler::fingerprint]     err: current filesystem status shows we're outdated
[2019-09-28T11:28:23Z INFO  cargo::core::compiler::fingerprint] fingerprint error for mozjs_sys v0.67.1 (/home/simon/projects/mozjs)/RunCustomBuild/Target { ..: custom_build_target("build-script-build", "/home/simon/projects/mozjs/build.rs", Edition2015) }
[2019-09-28T11:28:23Z INFO  cargo::core::compiler::fingerprint]     err: current filesystem status shows we're outdated
   Compiling mozjs_sys v0.67.1 (/home/simon/projects/mozjs)
    Finished dev [unoptimized + debuginfo] target(s) in 17.78s
    Finished dev [unoptimized + debuginfo] target(s) in 0.32s
```

</details>

**Comment by nox** [comment]
psutil's Makefile does that:

https://github.com/servo/mozjs/blob/3cfd5e764ea458f759192722a183ff0f235691dc/mozjs/third_party/python/psutil/Makefile#L69-L70

But AFAIK we let virtualenv install psutil on its own:

https://github.com/servo/mozjs/blob/3cfd5e764ea458f759192722a183ff0f235691dc/mozjs/build/virtualenv_packages.txt#L29

I can't find where psutil's own build system creates that silly tmp folder.

**Comment by nox** [comment]
Hey @giampaolo, do you remember why you wrote [this commit](https://github.com/giampaolo/psutil/commit/f4d6d9a3f93a4a334a7c6c751fb98cb81033d754)? We are trying to track down where that `tmp` directory is coming from.

**Comment by nox** [comment]
If I go in our in-tree psutil folder and run `make build` with the `rm -rf tmp` part commented-out, I don't even end up with a `tmp` folder.

**Comment by giampaolo** [comment]
@nox I remember at some point a tmp directory was created by “something” when I worked on psutil. And no, psutil source code/tests is not supposed to create a dir with that name so it was/is probably something with my environment. I think I will remove that line and see what happens.

**Comment by nox** [comment]
> I think I will remove that line and see what happens.

Don't be so quick to delete it, given this issue states that it is still happening hah.

**Comment by nox** [comment]
[Tentative fix](https://github.com/giampaolo/psutil/pull/1597) for psutil itself.

**Comment by nox** [comment]
I've reported the issue and fix on [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1584813) too.

**Comment by SimonSapin** [comment]
Also, `mozjs/third_party/python/psutil/tmp` is in `.gitignore`. Maybe Cargo should therefore ignore it for the purpose of staleness tracking?

**Comment by nox** [comment]
I would think that would be weird, given we explicitly tell it to rebuild when this path changes, thanks to this code:

https://github.com/servo/mozjs/blob/3cfd5e764ea458f759192722a183ff0f235691dc/build.rs#L133-L136

We could use [gitignore](https://crates.io/crates/gitignore) to not ask Cargo to rebuild on changes in ignored paths though.

**Comment by nox** [comment]
Or maybe not, I thought I could just use [`gitignore::File::is_excluded`](https://docs.rs/gitignore/1.0.6/gitignore/struct.File.html#method.is_excluded) but this method allocates the entire vector of included files on every call.

**Comment by nox** [comment]
We could otherwise use the [`ignore`](https://crates.io/crates/ignore) crate which seems more popular, but it offers parallel walk with `crossbeam-channel` and whatnot and this is not an optional feature, we probably don't want to bring all that stuff just to `println` some paths.

**Comment by nox** [comment]
Or we could just do [this](https://github.com/servo/mozjs/pull/203).
