### ISSUE TITLE
Add opt-in way to build on VS2019

### ISSUE THREAD

**Issue by saschanaz** [servo/mozjs#204]
From https://github.com/servo/servo/issues/24331

Since VS2019 supports VC++ 2017, forcing VS2017 makes me install another full copy of VC++ (and MSBuild etc.) because of the single line added by #197. Could we add an opt-in way to use VS2019?

![image](https://user-images.githubusercontent.com/3396686/65963117-10862e80-e495-11e9-9623-4cd2d3836b85.png)

Figure 1 - VS Build Tools 2019 provides VC++ 2017

**Comment by jdm** [comment]
This would require a cargo feature that is checked before configuring https://github.com/servo/mozjs/blob/master/makefile.cargo#L19.
