### ISSUE TITLE
mozjs fails during servo build

### ISSUE THREAD

**Issue by AW14Saurabh** [servo/mozjs#215]
The error I got

> --- stderr
> which: python2.7: unknown command
> ERROR: Visual Studio 2017 could not be found!
> mozmake: *** [makefile.cargo:197: maybe-configure] Error 1
> thread 'main' panicked at 'assertion failed: result.success()', C:\Users\aw14s\.cargo\git\checkouts\mozjs-fa11ffc7d4f1cc2d\5906588\build.rs:133:5
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

I have VS2019 installed and have v141 toolset (VS 2017)

**Comment by jdm** [comment]
You may be able to build servo with `--features vslatest` to avoid this.

**Comment by AW14Saurabh** [comment]
Build fails on glutin when I add that parameter

**Comment by jdm** [comment]
Sorry, vslatestinstalled:

**Comment by AW14Saurabh** [comment]
Done! Thanks a lot!
