### ISSUE TITLE
Tweak the _LIBCPP_INLINE_VISIBILITY patch so we can upstream it

### ISSUE THREAD

**Issue by nox** [servo/mozjs#222]
(@asajeffrey added this patch in #149.)

The configure code that sets this env variable in the moz.build stuff checks that the compiler is clang and the OS target is Android, as Alan said in the PR description.

I'm curious if the code could be tweaked to check the standard library rather than the compiler, which would allow us to upstream the patch more easily.

**Comment by jdm** [comment]
I think that's the wrong issue link?

**Comment by asajeffrey** [comment]
Try https://github.com/servo/mozjs/pull/180

**Comment by asajeffrey** [comment]
I'm not sure why we need any changes in what's being upstreamed, the patch just adds an env var for an already-existing configuration. All the stuff about Android, compilers, etc isn't in this patch.

**Comment by nox** [comment]
I'm just suspecting that the check that targets clang does so because it actually wants to target libc++, which is the default libc++ of clang. Could be wrong though.

**Comment by asajeffrey** [comment]
Could be, but that's probably an issue for upstream mozjs, not this crate?

**Comment by nox** [comment]
> Could be, but that's probably an issue for upstream mozjs, not this crate?

We are the one who wrote the patch, so I filed it here. I am not demanding immediate action, I had to file this somewhere to not forget it and I wasn't going to open a Bugzilla ticket.

**Comment by jdm** [comment]
The patch no longer exists.
