### ISSUE TITLE
Add bindings for RegExp flags

### ISSUE THREAD

**Issue by teapotd** [servo/mozjs#223]
https://github.com/servo/mozjs/blob/e21c05b415dfc246175ff8d5fc48b0e8c5b4e9e9/mozjs/js/src/builtin/SelfHostingDefines.h#L93-L97

These are needed for https://github.com/servo/servo/pull/25447 (pattern mismatch checking requires JS RegExp with unicode flag). [JS_NewRegExpObject](https://github.com/servo/mozjs/blob/e21c05b415dfc246175ff8d5fc48b0e8c5b4e9e9/mozjs/js/src/jsapi.h#L3176-L3184) expects those flags as argument.

**Comment by jdm** [comment]
We'll need to add some `const` statements by hand, then. I suggest a `mod jsregex {}` in lib.rs.
