### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_icudt65_dat",

### ISSUE THREAD

**Issue by coocooooo** [servo/mozjs#243]
command: cargo test

branch: master

os: macos Catalina 10.15.4

clang version 10.0.0

```
error: linking with `cc` failed: exit code: 1
...
= note: Undefined symbols for architecture x86_64:
            "_icudt65_dat", referenced from:
                openCommonData(char const*, int, UErrorCode*) in libjs_static.a(udata.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by anuragkalia** [comment]
I faced the same problem. It looks like a problem with servo's build at the first glance (not very familiar with servo build process so can be wrong). After running `nm` on the culprit file, I found that it is a symbol exported by `icu4c`. And probably depends on the version. The native library found in `/usr/lib/libicucore.dylib` defined `_icudt64_dat`. The one after brew install found in `/usr/local/opt/icu4c/lib/libicudata.67.dylib` defined `_icudt67_dat`.

I found the relevant `_icudt65_dat` being exported in `/path/to/servo/target/debug/build/mozjs_sys-0ae86c8a61f3690e/out/build/config/external/icu/data/icudata_gas.o`.

Trying to figure out if the file is present, why is it not automatically available to clang's linker through mach.

**Comment by jdm** [comment]
Based on [this chat log](https://chat.mozilla.org/#/room/#servo:mozilla.org/$T5tuKb4MGz7JL1fWvQIfb8hjlMs-4xDQzNz3XJFv-TQ), I believe that the wrong assembler is being used in your build. See my suggestion at https://github.com/servo/servo/issues/27240#issuecomment-657355386.

**Comment by coocooooo** [comment]
thank you saved my lift
