### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by Grishy** [servo/mozjs#248]
Today I checked my computer for viruses and found:

Processed objects |   |   |   |  
-- | -- | -- | -- | --
/Users/grishy/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/5906588/mozjs/js/src/tests/non262/pipeline/parse-error.js | Deleted | Trojan | HEUR:Trojan-Downloader.Script.Generic | 2020-04-23 15:18:36 +03:00

**kaspersky internet security**

**Comment by jdm** [comment]
Looks like Kaspersky is incorrectly flagging a test file as a virus. There's nothing that we're in a position to do about that.
