### ISSUE TITLE
What is relation between Mozilla-central js/rust and this mozjs crate?

### ISSUE THREAD

**Issue by sagudev** [servo/mozjs#261]
Could mozjs use Mozilla-centrals build.rs and other files for easier version bumps?

I'm talking about: https://searchfox.org/mozilla-central/source/js/rust

**Comment by jdm** [comment]
An earlier revision of this repo was integrated into mozilla-central, but they weren't kept in sync since then. It's easier for Servo to make necessary changes without going through mozilla-central, so I don't expect any reintegration to occur.
