### ISSUE TITLE
Remove python2 build requirement

### ISSUE THREAD

**Issue by jdm** [servo/mozjs#262]
Updating to the latest mozilla-central release should remove any python2 build requirements.

**Comment by jdm** [comment]
https://github.com/servo/mozjs/tree/smuppy2

**Comment by jdm** [comment]
Status: mac & windows non-debugmozjs builds succeed on CI. linux builds fail with:
```
--- stderr

  Traceback (most recent call last):

    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main

      return _run_code(code, main_globals, None,

    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code

      exec(code, run_globals)

    File "/home/travis/build/servo/mozjs/mozjs/python/mozbuild/mozbuild/action/file_generate.py", line 156, in <module>

      sys.exit(log_build_task(main, sys.argv[1:]))

    File "/home/travis/build/servo/mozjs/mozjs/python/mozbuild/mozbuild/action/util.py", line 18, in log_build_task

      return f(*args, **kwargs)

    File "/home/travis/build/servo/mozjs/mozjs/python/mozbuild/mozbuild/action/file_generate.py", line 87, in main

      spec.loader.exec_module(module)

    File "<frozen importlib._bootstrap_external>", line 783, in exec_module

    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

    File "/home/travis/build/servo/mozjs/mozjs/js/src/jit/GenerateCacheIRFiles.py", line 8, in <module>

      import yaml

  ModuleNotFoundError: No module named 'yaml'

  make[3]: *** [backend.mk:76: js/src/jit/.deps/CacheIROpsGenerated.h.stub] Error 1
```

mac/windows debugmozjs fails with:
```
rror[E0432]: unresolved import `jsapi::mozilla::detail::GuardObjectNotificationReceiver`

  --> src/jsimpls.rs:25:5

   |

25 | use jsapi::mozilla::detail::GuardObjectNotificationReceiver;

   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `GuardObjectNotificationReceiver` in `generated::root::mozilla::detail`

error[E0560]: struct `JSAutoRealm` has no field named `_mCheckNotUsedAsTemporary`

   --> src/jsimpls.rs:168:13

    |

168 |             _mCheckNotUsedAsTemporary: GuardObjectNotificationReceiver {

    |             ^^^^^^^^^^^^^^^^^^^^^^^^^ `JSAutoRealm` does not have this field

    |

    = note: available fields are: `cx_`, `oldRealm_`

error: aborting due to 2 previous errors
```

**Comment by jdm** [comment]
rust-mozjs branch that passes tests locally on macOS: https://github.com/servo/rust-mozjs/pull/new/smuppy2

**Comment by jdm** [comment]
Windows rust-mozjs failure:
```
rror: failed to get `mozjs_sys` as a dependency of package `mozjs v0.13.0 (C:\projects\rust-mozjs)`
Caused by:
  failed to load source for dependency `mozjs_sys`
Caused by:
  Unable to update https://github.com/servo/mozjs?branch=smuppy2
Caused by:
  failed to stat 'C:/Users/appveyor/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/a94d666/mozjs/js/src/tests/test262/built-ins/Object/seal/object-seal-the-configurable-attribute-of-own-data-property-of-o-is-set-from-true-to-false-and-other-attributes-of-the-property-are-unaltered.js': The filename or extension is too long.
```

**Comment by tomoverlund** [comment]
> linux builds fail with: ... ModuleNotFoundError: No module named 'yaml'

Looks to be a bug in version 84. The directory third_party/python/PyYAML/ does not exist, but is specified in build/common_virtualenv_packages.txt. It reappears in version 85, the latest package:

https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/X8EQrmqcQ8Sm_0H9GNK9Bg/runs/0/artifacts/public/build/mozjs-85.0.0.tar.xz

**Comment by tomoverlund** [comment]
> Looks to be a bug in version 84. The directory third_party/python/PyYAML/ does not exist, but is specified in build/common_virtualenv_packages.txt. It reappears in version 85, the latest package:

Actually, I take this back. Looks like a case-sensitivity issue on Linux versus Windows. I guess you uploaded from Windows, which destroyed the required uppercasing on Linux.

**Comment by tomoverlund** [comment]
I'm happy to report after moving:

mozjs/third_party/python/pyyaml/ to
mozjs/third_party/python/PyYAML/

and backing out your debugging statements in

mozjs/js/src/jit/GenerateCacheIRFiles.py

that mozjs builds and tests fine under Linux. All build and test commands in the README appear to work properly:

cargo build
cargo test
cargo build --features debugmozjs
cargo test --features debugmozjs

**Comment by jdm** [comment]
@tomoverlund I'm not sure I understand - in the smuppy2 branch, mozjs/third_party/python/PyYAML/ already exists, and build/common_virtualenv_packages.txt uses the same case. What change did you make?

**Comment by jdm** [comment]
Oh - https://github.com/servo/mozjs/tree/smuppy2/mozjs/third_party/python/pyyaml doesn't match what my local development tree contains:
```
godot:mozjs jdm$ ls -la mozjs/third_party/python/PyYAML
total 80
drwxr-xr-x  12 jdm  staff    384 Jan 17 10:47 .
drwxr-xr-x  74 jdm  staff   2368 Jan 17 10:47 ..
-rw-r--r--   1 jdm  staff  10672 Jan 17 10:47 CHANGES
-rw-r--r--   1 jdm  staff   1101 Jan 17 10:47 LICENSE
-rw-r--r--   1 jdm  staff   1781 Jan 17 10:47 PKG-INFO
-rw-r--r--   1 jdm  staff   1548 Jan 17 10:47 README
drwxr-xr-x   4 jdm  staff    128 Jan 17 10:44 examples
drwxr-xr-x   6 jdm  staff    192 Jan 17 10:47 ext
drwxr-xr-x   3 jdm  staff     96 Jan 17 10:44 lib
drwxr-xr-x   3 jdm  staff     96 Jan 17 10:44 lib3
-rw-r--r--   1 jdm  staff    793 Jan 17 10:47 setup.cfg
-rw-r--r--   1 jdm  staff  10170 Jan 17 10:47 setup.py
```
That's very strange.

**Comment by tomoverlund** [comment]
> That's very strange.

Looks like they changed the case upstream at Mozilla at some point.

**Comment by jdm** [comment]
No more python2.x.
