### ISSUE TITLE
Are the mozjs_sys and js crates useful in the spidermonkey source tree?

### ISSUE THREAD

**Issue by glandium** [servo/mozjs#270]
@jdm, since you've been responsive to my PRs here, I think you may have missed a needinfo in Mozilla's bugzilla, in https://bugzilla.mozilla.org/show_bug.cgi?id=1694318

My observations are that:
- the job we have on the Mozilla side that uses the js crate (the one in js/rust) only don't fail because it does 2 builds one after the other (one with --feature debugmozjs and the other without) without cleaning up, and the second only works because the first left things that make it work, so cleaning up between them, or inverting their order break things. AFAICT, this is a consequence of spidermonkey itself building rust code in a static library. Somehow it works for the debug build, but I think it only works by chance (and that's on top of the fact that it builds at all despite a possible race condition that, in fact, seems to happen when I switch from cmake to cc (cf. bugzilla)).
- the job we have that uses the mozjs_sys crate (which is the one in js/src) don't fail only because it's an rlib, and there is actually nothing that tries to use it, which would lead to the same error.
- the content of both crates is now very different from what servo now has.

So the question in bugzilla boils down to this: do we need to keep these on the Mozilla side?

**Comment by jdm** [comment]
Answered in Bugzilla. You're free to remove them.

**Comment by glandium** [comment]
For the record, you'll probably have a hard time trying to make mozjs work with jsrust enabled.
