### ISSUE TITLE
Merge mozjs and rust-mozjs into one repo

### ISSUE THREAD

**Issue by sagudev** [servo/mozjs#297]
Apparently this was suggested multiple times [according to Simon Sapin](https://servo.zulipchat.com/#narrow/stream/263398-general/topic/Spidermonkey.20upgrade/near/252016272). As already stated in zulip I am willing to help with it after #295 lands.

**Comment by jdm** [comment]
Very much in favour of this happening!

**Comment by sagudev** [comment]
After merging we should have on CI running on UWP.

**Comment by Redfire75369** [comment]
https://hacks.mozilla.org/2022/08/merging-two-github-repositories-without-losing-commit-history/
Since we presumably want to keep the commit history of both, following something like this which MDN did should be helpful.

**Comment by sagudev** [comment]
Actually I was thinking of archiving rust-mozjs (so we keep it's history there) and merge it into this repo in just one step/commit. That way the users that use rust-mozjs or mozjs repo in their Cargo would still have working Cargo.toml.
