### ISSUE TITLE
CI broken with mozilla-build 4.0

### ISSUE THREAD

**Issue by jdm** [servo/mozjs#300]
```
     Running `D:\a\mozjs\mozjs\target\debug\build\mozjs_sys-429806b452f72395\build-script-build`
[mozjs_sys 0.68.2] cargo:outdir=D:\a\mozjs\mozjs\target\debug\build\mozjs_sys-c3e02811bd22dd0e\out\build
[mozjs_sys 0.68.2] gmake: *** No targets specified and no makefile found.  Stop.
[mozjs_sys 0.68.2] thread 'main' panicked at 'Failed to run `make`: Error { kind: NotFound, message: "program not found" }', build.rs:177:10
[mozjs_sys 0.68.2] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I believe this is because msys64 isn't placed in the path by default in the new environment (see note in https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md). The easiest way to deal with this is probably via https://github.com/msys2/setup-msys2

**Comment by jdm** [comment]
This is impacting the windows-2019 environment as well for reasons that I don't understand.

**Comment by jdm** [comment]
This is actually caused by the release of Mozilla-Build 4.0 last week: https://groups.google.com/a/mozilla.org/g/dev-platform/c/0GHhML7tY6c . If we update, we'll need to address that.

**Comment by sagudev** [comment]
integrity check is also broken, either taskcluster changed their api (unlikly) or previous build is out of cache.

**Comment by jdm** [comment]
That's a very old issue; the taskcluster API returns an error for something that it shouldn't, and the taskcluster team didn't look into when I raised it on Matrix.

**Comment by sagudev** [comment]
It's actually treeherder. My bad.

**Comment by sagudev** [comment]
Probably out of cache, their retention is 6 or 9 months I guess.
