### ISSUE TITLE
Windows CI breaks when the environment's LLVM doesn't match the version installed by scoop

### ISSUE THREAD

**Issue by jdm** [servo/mozjs#302]
Keeping up with this requires changing the explicit version installed by scoop (eg. `llvm@13.0.1`) whenever the Windows virtual environment updates with a new LLVM version: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md

**Comment by sagudev** [comment]
Maybe try https://github.com/marketplace/actions/install-clang or https://github.com/marketplace/actions/install-llvm-and-clang

**Comment by sagudev** [comment]
Here is something interesting: https://github.com/egor-tensin/setup-clang/blob/master/.github/workflows/test.yml#L22
They apparently clear whole path before using clang. Maybe we only need to remove windows llvm from path.

**Comment by jdm** [comment]
I experimented with https://github.com/marketplace/actions/install-llvm-and-clang in https://github.com/servo/mozjs/pull/299, but that was before I figured out the issues around MozillaBuild 4.0.

**Comment by sagudev** [comment]
It would still be nice to have it done properly not with scoop, which gives more trouble now than solutions.

**Comment by sagudev** [comment]
Maybe it's not Windows virtual environment Rust, that is causing these errors. One solution that I could think of is using `rustc -vV | sed -n 's|LLVM version: ||p'` to extract Rust's LLVM version and install the same version in the Windows CI with scoop.

**Comment by jdm** [comment]
> Maybe it's not Windows virtual environment Rust, that is causing these errors. One solution that I could think of is using `rustc -vV | sed -n 's|LLVM version: ||p'` to extract Rust's LLVM version and install the same version in the Windows CI with scoop.

I don't think there's any evidence that the version of LLVM used by Rust is to blame. The issue is header files present in MSVC, as far as I can recall.

**Comment by Redfire75369** [comment]
Based on <https://github.com/Redfire75369/spiderfire/actions/runs/4497451094/jobs/7913055028>, MSVC and the version of LLVM 15.0.7 on the system definitely seem to be the issue. (Installed LLVM 14.0.6 with scoop)

```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.35.32215\include\yvals_core.h:807:1: error: static_assert failed "Error in C++ Standard Library usage.", err: true
C:\Program Files\LLVM\lib\clang\15.0.7\include\emmintrin.h:2108:19: error: use of undeclared identifier '__builtin_elementwise_add_sat', err: true
C:\Program Files\LLVM\lib\clang\15.0.7\include\emmintrin.h:2129:19: error: use of undeclared identifier '__builtin_elementwise_add_sat', err: true
C:\Program Files\LLVM\lib\clang\15.0.7\include\emmintrin.h:2149:19: error: use of undeclared identifier '__builtin_elementwise_add_sat', err: true
C:\Program Files\LLVM\lib\clang\15.0.7\include\emmintrin.h:2169:19: error: use of undeclared identifier '__builtin_elementwise_add_sat', err: true
C:\Program Files\LLVM\lib\clang\15.0.7\include\emmintrin.h:2528:19: error: use of undeclared identifier '__builtin_elementwise_sub_sat', err: true
C:\Program Files\LLVM\lib\clang\15.0.7\include\emmintrin.h:2548:19: error: use of undeclared identifier '__builtin_elementwise_sub_sat', err: true
C:\Program Files\LLVM\lib\clang\15.0.7\include\emmintrin.h:2567:19: error: use of undeclared identifier '__builtin_elementwise_sub_sat', err: true
C:\Program Files\LLVM\lib\clang\15.0.7\include\emmintrin.h:2586:19: error: use of undeclared identifier '__builtin_elementwise_sub_sat', err: true
```

**Comment by sagudev** [comment]
When looking at error, notice how it uses clang/15.0.7 when the installed version from scoop is 14.0.6
I believe that there is something wrong with one of build.rs scripts at least on windows that uses the wrong compiler.
