### ISSUE TITLE
Where is JSContext defined as an opaque type?

### ISSUE THREAD

**Issue by kha-dinh** [servo/mozjs#330]
I am studying how the jsapi bindings are generated.
I found that there are opaque types that are not defined in build.rs. 
For instance, JSContext is an opaque type in the generated binding, but not listed in OPAQUE_TYPE within [mozjs/build.rs](https://github.com/servo/mozjs/blob/master/mozjs/build.rs).

    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct JSContext {
        _unused: [u8; 0],
    }``
Is there any other ways that those types could be defined as opaque types, or are they inferred automatically by bindgen?
I would very much appreciate any help.

**Comment by jdm** [comment]
I suspect it's because bindgen's definitions on rely on the public headers, where JSContext is only ever defined as `struct JSContext;` like [this code](https://github.com/servo/mozjs/blob/0623d5fced66007ec7a35d1ca9a3cfd1b30f27f9/mozjs/mozjs/js/public/PropertyAndElement.h#L21).

**Comment by kha-dinh** [comment]
I think it is the case. Thank you for replying, I am closing this issue.
