### ISSUE TITLE
error: failed to get `mozjs` as a dependency of package `script v0.0.1 on windows11 system

### ISSUE THREAD

**Issue by peterwa88** [servo/mozjs#331]
I built servo and got the following error, I reset the system configuration to accept long path name, however still get the same error. Please help! THX

PS C:\workspace\servo3> ./mach build --dev --verbose
info: component 'llvm-tools' for target 'x86_64-pc-windows-msvc' is up to date
rustup.exe run --install nightly-2022-11-20-x86_64-pc-windows-msvc cargo build --manifest-path C:\workspace\servo3\ports\winit\Cargo.toml --features media-gstreamer native-bluetooth egl layout-2013 --timings -v
error: failed to get `mozjs` as a dependency of package `script v0.0.1 (C:\workspace\servo3\components\script)`

Caused by:
  failed to load source for dependency `mozjs`

Caused by:
  Unable to update https://github.com/servo/mozjs#f87705d6

Caused by:
  path too long: 'C:/Users/Administrator/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/f87705d/mozjs/mozjs/js/src/tests/test262/language/expressions/class/async-gen-method-static/forbidden-ext/b2/cls-expr-async-gen-meth-static-forbidden-ext-indirect-access-own-prop-caller-value.js'; class=Filesystem (30)
[Warning] Could not generate notification! 
Build FAILED in 0:02:20

**Comment by jdm** [comment]
@peterwa88 You can use `cargo update -p mozjs` in Servo to get the newest changes and see if that improves the situation.

**Comment by peterwa88** [comment]
"cargo update -p mozjs" worked. Thanks a lot, Josh Matthews!

**Comment by vegchic** [comment]
It occurs again... caused by another file, located in `.../language/statements/class/...` 

```
Caused by:
  path too long: 'D:/Scoop/persist/rustup/.cargo/git/checkouts/mozjs-fa11ffc7d4f1cc2d/b9edc81/mozjs/mozjs/js/src/tests/test262/language/statements/class/async-gen-method-static/forbidden-ext/b2/cls-decl-async-gen-meth-static-forbidden-ext-indirect-access-own-prop-caller-value.js'; class=Filesystem (30)
```

**Comment by sagudev** [comment]
Do we even need `js/src/tests/test262`?

**Comment by jdm** [comment]
We don't run the tests ourselves, so they're dead weight.
