### ISSUE TITLE
The Integrity check is currently broken

### ISSUE THREAD

**Issue by sagudev** [servo/mozjs#345]
Integrity checks are failing again due to missing SM pkg, so I've asked on SpiderMonkey Matrix about more permanent SM pkgs and [they said that SM packages are not recommended way of using SM](https://matrix.to/#/!CZEbuMfGYVdQMIBKeP:mozilla.org/$lLzrgflV1kUvMonPfMPgwHU9y34pvFrQ3e4B1ohN-TI?via=mozilla.org&via=matrix.org&via=igalia.com), so they do not plan to host them on ftp anytime soon.

Here are few possible solutions for going forward:
1. Do nothing and keep Integrity check as optional (so commits are merged even if check fails)
2. Use whole mozilla-source for SM
3. Host used SM pkgs somewhere (maybe as GitHub releases)
4. Follow ESR cycle (thus never falling behind for more than 3 months = time that SM pkgs are available)

The last one may be the best for servo as porting ESR patches should not be as hard as usual SMups and following ESR would keep SM properly patched. ESR version are released once per year and they usually come with [Migration Guides](https://github.com/mozilla-spidermonkey/spidermonkey-embedding-examples/blob/esr102/docs/Migration%20Guide.md) and there are other users of SM which are also doing upgrades (most notably [gjs](https://gitlab.gnome.org/GNOME/gjs)) which could help our upgrades. The only problem are slower features rollout, but current servo development may benefit from less SM breaking changes so there could be more focus on other parts.

**Comment by jdm** [comment]
ESR does sound like the way to go.

**Comment by Redfire75369** [comment]
Given that I'm writing a runtime, my perspective on this is slightly different. It would be really nice to be able to release a version with, for example, the top level await stabilised in SM 97 or WebAssembly Garbage Collection stabilised in SM 111, and get the intermediate performance improvements. I fully understand that every other embedding of spidermonkey uses the ESRs, but I'm not sure that's the best approach for my project at the least.
