### ISSUE TITLE
How to listen for JS Errors in rust?

### ISSUE THREAD

**Issue by Throvn** [servo/mozjs#348]
To my understanding you set up a `JS_SetErrorInterceptorCallback`. However, I cannot figure out how to create a fitting callback, since there always is a type mismatch. As far as I know, you have to create an instance of the `JSErrorInterceptor`, but how do I do that?

```rust
unsafe {
        JS_SetErrorInterceptorCallback(rt.rt(), /* what do H put in here, that I can handle the error in rust? */);
}
```

**Comment by jdm** [comment]
Based on https://doc.servo.org/mozjs/jsapi/struct.JSErrorInterceptor.html and https://github.com/servo/mozjs/blob/61353e372f9f4b1bf191ea2c0f88296fc7453763/mozjs/mozjs/js/public/ErrorInterceptor.h#L6, it looks like there would need to be new C bindings to support a error interceptor written in Rust.

This would require:
* an ErrorInterceptorTraps class in jsglue.cpp containing an `intercept_error` function pointer
* a RustErrorInterceptor class in jsglue.cpp that inherits from JS_ErrorInterceptor and contains an ErrorInterceptorTraps member
* a new function in jsglue.cpp to create a RustErrorInterceptor instance, returning `JSErrorInterceptor*`
* corresponding ErrorInterceptorTraps and creation function declarations in glue.rs

It would follow the same pattern as [this code](https://github.com/servo/mozjs/blob/master/rust-mozjs/src/jsglue.cpp#L43-L83) and [CreateJobQueue](https://github.com/servo/mozjs/blob/master/rust-mozjs/src/glue.rs#L572).

**Comment by Redfire75369** [comment]
From my conversations in the [matrix channel](https://matrix.to/#/!CZEbuMfGYVdQMIBKeP:mozilla.org/$NRaMJdnQh68w0xg73JMp4bWCSbk_wGQoiC9VROGiaWY?via=mozilla.org&via=matrix.org&via=igalia.com), `JS_SetErrorInterceptorCallback` was meant for nightly only and should not be used by embedders.

> That should not be used at all probably 
> I wonder if the error inception is used at all at the moment, maybe we can remove it
> Yes. I think this was added for some kind of telemetry on Nightly to detect new JavaScript errors. I am however not sure if we still have or use that telemetry based on this code

**Comment by Throvn** [comment]
Thank you, the both of you.
@Redfire75369 you seemed to have the same problem, how did you solve it?

Recently, I came accross `JS_IsExceptionPending(cx)` and `JS_GetPendingException(...)`. However, I'm wondering whether you can catch **all** exceptions with that? 
Is it sufficient to just check it after `runtime.evaluate_script(...)` (that's what I'm doing currently and it does seem to work) or does this leave some errors hidden?

**Comment by jdm** [comment]
As far as I know that's what you want. I'm not aware of hidden exceptions in the engine.

**Comment by Redfire75369** [comment]
The JS engine only has 1 exception at a time, so it'll keep only one at a time. If the exception is caught, it won't be recorded.

Any exception that bubbles all the way to the top layer and isn't caught stops execution, so it'll only ever have a single exception. You can just check for that after each evaluation of a script.

If you're using top-level await, you'll need to change it slightly so you add a promise reaction with `AddPromiseReactions` (for rejected promises) so you have access to the rejection message/object.

I never actually dealt with my problem, just that I decided not to worry about it directly.
