### ISSUE TITLE
malformed config/autoconf.mk

### ISSUE THREAD

**Issue by charlesxsh** [servo/mozjs#361]
When building the mozjs_sys, there is a error due to the malformed autoconf.mk:

```
PATH = /Library/Frameworks/GStreamer.framework/Versions/1.0/bin:/Users/sxia/code/servo/python/_virtualenv3.9/bin:Unknown command: "bin"

To see a list of supported npm commands, run:
  npm help:/Users/sxia/.nvm/versions/node/v16.17.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/sxia/Library/Python/3.9/bin:Unknown command: bin To see a list of supported npm commands, run: npm help:/Users/sxia/.nvm/versions/node/v16.17.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/sxia/.cargo/bin:/Users/sxia/.foundry/bin:/Users/sxia/.foundry/bin:/Users/sxia/.foundry/bin
PERL = /usr/bin/perl
```

As you can see, the PATH variable is malformed with the error message from node.

**Comment by sagudev** [comment]
Do you have autoconf2.13?

**Comment by charlesxsh** [comment]
> Do you have autoconf2.13?

Yes. And in my opinion(just guess), this output is more like when generating the autoconf.mk, the script run a incorrect npm command and paste the result to the PATH variable without checking status code

**Comment by sagudev** [comment]
I think we shouldn't need npm in the first place.

Could you post whole autoconf.mk file.

**Comment by sagudev** [comment]
Try using bash shell.

**Comment by charlesxsh** [comment]
Do you think the issue is caused by zsh?

**Comment by sagudev** [comment]
It certainly could.

**Comment by charlesxsh** [comment]
Would you elaborate more? Like point out where the npm command is called in the Python script?
________________________________

**Comment by sagudev** [comment]
That's the funny thing. Npm command shouldn't be called in build process at all. Something does indeed goes wrong when setting PATH var and that's where npm gets called (coincidentally path is wrong at nvm/node bin path). I believe autoconf uses shell for evaluation and wrong shell can lead to wrong results.

**Comment by charlesxsh** [comment]
Oh yes it is indeed my zsh profile is wrong...fixed it
