### ISSUE TITLE
Incorrect Download Instructions for Windows

### ISSUE THREAD

**Issue by Redfire75369** [servo/mozjs#397]
Following the instructions as stated in the readme, specifically the following, does not work.
> Install [MozillaBuild 4.0](https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-4.0.2.exe) or download and unzip [MozTools 4.0](https://github.com/servo/servo-build-deps/releases/download/msvc-deps/moztools-4.0.zip).

If one downloads MozillaBuild 4.0 as the first half suggests, the build will fail as `mozmake` is not found. Finding and downloading `mozmake` is not easy so adding just it to [servo/servo-build-deps](https://github.com/servo/servo-build-deps) could be a solution.

**Comment by sagudev** [comment]
We could just put TC link, but it's compressed using zstd and 7z does not support it. MozTools should be recommended approach and MozillaBuild for "advance" users.

**Comment by mrobinson** [comment]
I think it makes sense to have only a single way of building, if possible. @Redfire75369 do you have issues with using MozTools instead of MozillaBuild?

**Comment by Redfire75369** [comment]
Not particularly. If needed, one can just set `MOZTOOLS_PATH` to `C:\mozilla-build`  with `mozmake` in the correct sub-directory anyway.
