### ISSUE TITLE
generate_wrappers.sh only works on Clean Builds

### ISSUE THREAD

**Issue by Redfire75369** [servo/mozjs#398]
Due to various reasons, it is possible for the `target` directory to contain multiple versions of the build directories for `mozjs_sys` and `mozjs`. This causes the following lines in [`generate_wrappers.sh`](https://github.com/servo/mozjs/blob/master/rust-mozjs/src/generate_wrappers.sh) to fail as multiple versions of  `jsapi.rs`/`gluebindings.rs` are found.

<https://github.com/servo/mozjs/blob/6b299dec6b9421a903ef3ce752b957b3473c0b1c/rust-mozjs/src/generate_wrappers.sh#L31-L34>

Although running `cargo clean` every time is not the worst, it would probably be better for `generate_wrappers.sh` to detect the most recently modified one. I'm trying to work on a solution but my shell skills are insufficient.

**Comment by sagudev** [comment]
I noticed the same problem. Also we require debug build. I think I could make it using `find`.
