### ISSUE TITLE
Build Failure on Windows with LLVM 17.0.1

### ISSUE THREAD

**Issue by Redfire75369** [servo/mozjs#410]
```bat
  error: unsupported option '-G' for target 'x86_64-pc-windows-msvc'
  # ...
  thread 'main' panicked at 'Unable to generate bindings to jsglue: ClangDiagnostic("error: unsupported option '-G' for target 'x86_64-pc-windows-msvc' ...)
```
Not sure why this happens, but updating from 16.0.6 caused this issue.

Full Log with `-v`: <https://paste.gg/p/redfire/0ec149108e884db08c0bd9ca052645a7>

**Comment by sagudev** [comment]
Root cause:
https://github.com/servo/mozjs/blob/d968433faa139038e368981d024a2065f22e93fb/rust-mozjs/build.rs#L87

Try removing that line.

**Comment by sagudev** [comment]
`/GR-` is for clang-cl, maybe that's where problem lies

**Comment by sagudev** [comment]
or maybe not:
> To be compatible with cl.exe, clang-cl supports most of the same command-line options. Those options can start with either / or -. It also supports some of Clang’s core options, such as the -W options.

from https://clang.llvm.org/docs/UsersManual.html#id10

**Comment by Redfire75369** [comment]
The issue is in `bindgen::generate`, which seems to be `libclang`. Specifically, `clang_parseTranslationUnit` adds a `clang` to the command line args. I'm still not sure why llvm 17 specifically would fail however.

**Comment by Redfire75369** [comment]
Found a solution, adding `-fms-compatibility` to the flags.

**Comment by Redfire75369** [comment]
I've been looking into this again, and `-fms-compatibility` isn't actually needed (although we should probably add it). On the other hand, `-GR-` was also not doing anything. Since `clang` (not `clang-cl`) does not understand it, it was silently ignored. However, this seems to have changed with LLVM 17, where unknown flags can now cause errors if a specific target is passed, in this case `x86_64-pc-windows-msvc`.

As such, the solution is just to remove the `-GR-`. We could probably add `-fno-rtti`, if we specifically need that functionality.

LLVM Commit: <https://github.com/llvm/llvm-project/commit/a79995ca6004082774a87f7a58ab6be5343364b7#diff-a1ed50d19437e4d0f0e14deb2d305bbd3e8537285fdf7466f27216236d94384a>
Code in Question: https://github.com/llvm/llvm-project/blob/241848b9b1a1c7254b83beac7a88085787036c72/llvm/include/llvm/Option/Arg.h#L50-L55

**Comment by sagudev** [comment]
Good find!
