### ISSUE TITLE
Make ‎TypedArray::update safe

### ISSUE THREAD

**Issue by gterzian** [servo/mozjs#446]
I think [`‎TypedArray::update`](https://github.com/servo/mozjs/blob/7184f658b7e2de8a8d288ff39001364513115782/mozjs/src/typedarray.rs#L255) can be made safe, while containing an unsafe block calling `Self::update_raw`, that way we can remove these [kind of unsafe blocks](https://github.com/servo/servo/pull/30990/files#diff-88b03ac9bcc2650883607d41bc374d7f3976567cfbee702cc124f14ce2fbc79bR283) in Servo.

**Comment by Taym95** [comment]
How do you think we can do this @gterzian, from code I see unsafe code call is chained, update -> update_raw -> copy_nonoverlapping

**Comment by gterzian** [comment]
I think `update` should simply be safe externally, but internally have an unsafe block that calls `update_raw`.

**Comment by Taym95** [comment]
this can be closed.
