### ISSUE TITLE
AssertionError in virtualenv.py

### ISSUE THREAD

**Issue by siddhanathan** [servo/mozjs#47]
I'm currently using the Nix Package manager where the assertion in https://github.com/servo/mozjs/blob/058c207db8fe4316510ad8171d1ec5969a76fa7e/mozjs/python/virtualenv/virtualenv.py#L1083 won't be valid.

The output I get while trying to build servo contains the following:

~~~
failed to run custom build command for `mozjs_sys v0.0.0 (https://github.com/servo/mozjs#2c918d1f)`
Process didn't exit successfully: `/home/siddhu/Documents/servo/servo/target/release/build/mozjs_sys-e411d274df144795/build-script-build` (exit code: 101)
--- stdout
cd /home/siddhu/Documents/servo/servo/target/release/build/mozjs_sys-e411d274df144795/out && \
.
.
.
File "/home/siddhu/Documents/servo/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/python/virtualenv/virtualenv.py", line 1084, in change_prefix
    (filename, prefixes)
AssertionError: Filename /nix/store/8n4gpvl5z49ncpj0fisyr4ry8j6hy7qx-python-readline-2.7.10/lib/python2.7/site-packages/readline.so does not start with any of these prefixes: ['/nix/store/z6vp5aix4ks1zdjdry7v7dahg8dd02sy-python-2.7.10']
~~~

This isn't a big deal, since NixOS can patch this on their end. I just wanted to point out that this assertion won't be valid in a few corner cases.

**Comment by Ms2ger** [comment]
This code is unmodified from https://github.com/pypa/virtualenv, AIUI. You might want to file it there?

**Comment by siddhanathan** [comment]
Thanks! Will report it upstream.
