### ISSUE TITLE
try_compile does not respect `TARGET_CFLAGS` 

### ISSUE THREAD

**Issue by jschwe** [servo/mozjs#472]
While trying to cross-compile `servo` on a windows host, I noticed that the `mozjs` [try_compile](https://github.com/servo/mozjs/blob/7fe4fa20b6de000e1a0ddeb52237a7efffa018c7/mozjs-sys/mozjs/build/moz.configure/compile-checks.configure#L21) configure checks don't pass any flags from `TARGET_CFLAGS` or `TARGET_CXXFLAGS`, which in my case contain the sysroot. With the sysroot flag missing one of the `try_compile` checks fails, since it can't find a header file (features.h). I'm not sure why I don't experience this on my Linux machine - perhaps the compiler falls back to the host sysroot (which would also be wrong).

**Comment by jschwe** [comment]
Closing this issue. It seems that replacing backslashes with forward slashes (see #478) also causes all try_compile invocations to succeed again.

**Comment by sagudev** [comment]
NOTE-TO-SELF:

`TARGET_*` are respected here:
https://github.com/servo/mozjs/blob/728acdf3d4ce0604e9f75dd1d539dc6f291ccec7/mozjs-sys/build.rs#L1181
