### ISSUE TITLE
Add OpenHarmony support to Spidermonkey for logging 

### ISSUE THREAD

**Issue by jschwe** [servo/mozjs#487]
I have no idea how easy it would be to upstream changes like this, but the problem I'm facing is the following:

When spidermonkey encounters an error (E.g. a failed assertion）, it prints to stderr. 
I have [a PR](https://github.com/servo/servo/pull/32858) on the servo side which redirects stderr to the hilog logging system, but that uses a 2nd thread, which means that if the user sees the failed assertion is highly racy (does the logging thread log before the process dies).
Spidermonkey solves this on android by directly using `__android_log_print` and friends. We would probably need something like that too for OpenHarmony.

I guess Firefox currently probably does not have any plans to support OpenHarmony，but I'm wondering if they would accept pull requests adding OH support like above?

**Comment by jdm** [comment]
Best way to find out is to ask in their Matrix channel: https://chat.mozilla.org/#/room/#spidermonkey:mozilla.org

**Comment by jschwe** [comment]
Closing this issue since we already resolved this locally. Opened https://github.com/servo/mozjs/issues/498 to track upstreaming of the patches
