### ISSUE TITLE
jsglue sizeOfBuffer has UB in release mode

### ISSUE THREAD

**Issue by jschwe** [servo/mozjs#494]
When assertions are disabled, the function neither aborts nor returns a value resulting in UB: https://github.com/servo/mozjs/blob/ccd86bcc9dda834ee62f9f387dc956036fa8d559/mozjs-sys/src/jsglue.cpp#L176

**Comment by sagudev** [comment]
You're right! C(PP) is not rust :(. But this is not really problematic as nobody should actually call it as per assert it's not implemented. Proper implementation/fix is on the way with https://github.com/servo/mozjs/pull/481.

**Comment by jschwe** [comment]
> nobody should actually call it as per assert it's not implemented

Do we have any servo tests in CI that run with assertions in spidermonkey enabled?

> Proper implementation/fix is on the way with https://github.com/servo/mozjs/pull/481.

Thats great!

**Comment by sagudev** [comment]
> > nobody should actually call it as per assert it's not implemented
> 
> Do we have any servo tests in CI that run with assertions in spidermonkey enabled?

This is debugmozjs feature IIRC, but it isn't run, I plan to work on it sometime in the future.

> > Proper implementation/fix is on the way with #481.
> 
> Thats great!

This is done now so closing.
