### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by boghison** [servo/mozjs#50]
--- stderr
/home/bcuza/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: 1: /home/bcuza/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: /home/bcuza/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/../../python/mozbuild/mozbuild/milestone.py: Permission denied
/home/bcuza/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: 1: /home/bcuza/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: /home/bcuza/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/../../python/mozbuild/mozbuild/milestone.py: Permission denied
/home/bcuza/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: 1: /home/bcuza/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/configure: /home/bcuza/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/../../python/mozbuild/mozbuild/milestone.py: Permission denied
Reticulating splines...
Finished reading 34 moz.build files in 0.05s
Processed into 109 build config descriptors in 0.04s
Backend executed in 0.13s
80 total backend files; 0 created; 0 updated; 80 unchanged; 0 deleted; 10 -> 20 Makefile
Total wall time: 0.26s; CPU time: 0.25s; Efficiency: 95%; Untracked: 0.04s
make[5]: warning: -jN forced in submake: disabling jobserver mode.
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[4]: *** [Unified_cpp_js_src12.o] Error 4
make[4]: *** Deleting file 'Unified_cpp_js_src12.o'
make[4]: *** Waiting for unfinished jobs....
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[4]: *** [Unified_cpp_js_src10.o] Error 4
make[4]: *** Deleting file `Unified_cpp_js_src10.o'
make[3]: *** [js/src/target] Error 2
make[2]: *** [compile] Error 2
make[1]: *** [default] Error 2
make: *** [all] Error 2
thread 'main' panicked at 'assertion failed: result.success()', /home/bcuza/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/build.rs:16

**Comment by karyon** [comment]
any help on this would be greatly appreciated. i'm trying to build servo on ubuntu 15.10 with gcc 5.2 and failed with this error. gcc 4.7 does not help either.

**Comment by Manishearth** [comment]
Delete your `~/.cargo` folder and try again, it seems to be somewhat intermittent.

**Comment by jdm** [comment]
@karyon How much RAM is available when you're building?

**Comment by jdm** [comment]
and/or hard drive space.

**Comment by karyon** [comment]
deleting .cargo did not help. disk space was plenty. but i remembered the VM (windows host here...) had only 1GB RAM, but it still compiled with -j4, so i upped that to 4GB and now it got past compiling mozjs. seems like it went OOM... thanks for the hints!

**Comment by eefriedman** [comment]
Okay; I don't think there's anything to be done here... unless someone wants to add a warning to the servo README about RAM usage.
