### ISSUE TITLE
Investigate ohos release artifact size

### ISSUE THREAD

**Issue by jschwe** [servo/mozjs#508]
the OH artifact is 118MB large when zipped, 600MB uncompressed. 
It's likely that the strip command is not working correctly. 
We could read `STRIP` as an environment variable, allowing the user to set `llvm-strip`, or perhaps we could use `${CC}/../llvm-strip`  if `CC.endswith("clang")`.

**Comment by sagudev** [comment]
Given that we bindgen requires llvm I think we can safely assume that `llvm-strip` exists.

**Comment by jschwe** [comment]
On my macbook, `llvm-strip` is not in PATH, but `strip` is, so perhaps it's safer not to change start requiring llvm-strip right now.

**Comment by sagudev** [comment]
correction: bindgen requires libclang not llvm.
