### ISSUE TITLE
mozjs doesn't compile without the streams feature

### ISSUE THREAD

**Issue by jschwe** [servo/mozjs#527]
Without the streams feature I'm getting lots of errors like

```
error[E0432]: unresolved import `crate::jsapi::JS_GetFloat32ArrayData`
  --> mozjs/src/typedarray.rs:29:5
   |
29 | use crate::jsapi::JS_GetFloat32ArrayData;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `JS_GetFloat32ArrayData` in `jsapi`

```

**Comment by sagudev** [comment]
Hm, that's weird as CI is also testing case where streams are disabled and it passes.

**Comment by sagudev** [comment]
Also `JS_GetFloat32ArrayData` is not related to streams.

**Comment by jschwe** [comment]
You are right, it is not related to streams. Building works from servo, but not standalone. I'll have to investigate more.
