### ISSUE TITLE
--enable-gczeal snuck back in, and missing JSTracer::setTracingLocation etc. on win32

### ISSUE THREAD

**Issue by vvuk** [servo/mozjs#70]
--enable-gczeal was removed in https://github.com/servo/mozjs/commit/049d78d1b9df6ceeeaa1bd113cf89af49f9bfd0b but made its way back in the win32 commit at https://github.com/servo/mozjs/commit/446871d64803ef38eebeee0806ae695169c1e456 -- but only on non-win32 platforms.

On win32, when JS_GC_ZEAL is not defined, these are inline declared to be {} in public/TracingAPI.h.  But for some reason these functions are not making their way as public symbols in the output.

**Comment by larsbergstrom** [comment]
r? @michaelwu @jdm 

(since you were the two who looked at the previous bits)

**Comment by vvuk** [comment]
Pull request #71 solves this

**Comment by fitzgen** [comment]
https://github.com/servo/mozjs/pull/71 was merged.
